// lang-es.ts

export const LANG_KO_NAME = 'ko';

export const LANG_KO_TRANS = {
  'login': '로그인',
  'registration': '가입',
  'register' : '가입',
  'otp': '인증번호',
  'firstName': '이름',
  'lastName': '성',
  'email': '이메일 주소',
  'password': '비밀번호',
  'oldPassword': '이전 비밀번호',
  'newPassword': '새로운 비밀번호',
  'confirmPassword': '비밀번호 확인',
  'createAccount': '계정 만들기',
  'recover': '복구',
  'signUp': '가입하기',
  'verifyOTP': '인증번호 확인',
  'dntHaveAccount':'아직 계정이 없으신가요?',
  'forgotPwd':'계정 비밀번호를 잊어버리셨나요?',
  'alreadyAccount':'이미 계정이 있으신가요?',
  'home':'홈',
  'term':'약관',
  'blog':'블로그',
  'doYouQuestion':'질문이 있으신가요? hello@proofsuite.com으로 연락주세요.',
  'frstNameRqrd':'이름을 적어주세요.',
  'lastNameRqrd':'성을 적어주세요.',
  'frstNameLnth':'이름은 3자에서 50자 사이로 입력해주세요.',
  'lastNameLnth':'성은 2자에서 50자 사이로 입력해주세요.',
  'emailRqrd':'이메일을 입력해주세요.',
  'validEmail':'유효한 이메일을 입력해주세요.',
  'validPwd':'비밀번호는 적어도 대문자 한 자를 포함시켜 주세요.',
  'pwdLenth':'비밀번호는 8자에서 50자 사이로 입력해주세요.',
  'pwdRqrd':'비밀번호를 입력해주세요.',
  'cnfrmPwdRqrd':'비밀번호를 확인해 주세요.',
  'cnfrmPwdNtMatched':'비밀번호 확인이 일치하지 않습니다.',
  'otpRqrd':'인증번호를 입력해주세요.',
  'otpLnth':'인증번호는 6자리 숫자입니다.',
  'validOtp':'인증번호는 숫자로만 입력해주세요.',
  'terms1':' 본인은 미국 시민권자, 영주권자, 미국 법인 또는 시민을 대표하는 자가 아니며, SYM 토큰 구매가 불법이거나 제한적이거나 특별한 인가를 필요로 하는 관할권에 속한 회사를 대표하는 자 혹은 그 관할권의 영주권자가 아님을 확인합니다.',
  'termsAndCondition':'이용약관',
  'privacyPolicy':'개인 정보 보호 정책',
  'terms21':'본인은 을 읽고 이해했으며',
  'terms22':'본 약관에 기술된 모든 조건, 의무, 확인, 진술 및 보증을 명시적으로 수락하고 이에 동의합니다.',
  'terms31':'본인은 을 읽고 이해했으며',
  'terms32':'본 약관에 기술된 모든 조건, 의무, 확인, 진술 및 보증을 명시적으로 수락하고 이에 동의합니다.',
  'terms4':'본인은 를 읽고 이해했으며',
  'whitePaper':'백서',
  'termsOfTokenSale':'토큰 판매 조건',
  'countryCode':'국가를 코드',
  'phoneNumberRqrd':'전화번호를 입력하세요.',
  'countryRqrd':'국가를 입력하세요.',
  'mobileNumber':'휴대폰 번호',
  'country':'국가',
  'countryCodeRqrd':'국가 코드를 입력하세요.',
  'dashboard':'대시 보드',
  'transactionHistory': '거래 내역',
  'send':'보내기',
  'etherBalance':'이더 잔액',
  'thisTokenBalance':'토큰 잔액',
  'refresh':'새로고침',
  'addressInfo':'주소 정보',
  'settings':'설정',
  'logout':'로그아웃',
  'destinationRqrd':'보낼 주소를 입력해주세요.',
  'validDestination':'유효한 주소를 입력해주세요.',
  'amountRqrd':'금액을 입력해주세요.',
  'validAmount':'유효한 금액을 입력해주세요.',
  'landingTitle1' : '토큰 판매 마감:',
  'landingTitle' : '토큰 판매 시작',
  'days' : '일',
  'hours' : '시간',
  'minutes' : '분',
  'seconds' : '초',
  'subTitleLanding' : '현재까지 모인 금액',
  'subTitleInvestoren' : '참가자',
  'proof' : '프루프(SYM)',
  'SYM' : 'SYM',
  'completeTitle' : 'PROOF: TOKEN-AS-A-SERVICE',
  'completeSubTitle' : 'THE-FIRST-EVER TOKENZIED CLOSED-END FUND DEDICATED TO BLOCKCHAIN ASSETS',
  'homeLink' : '홈',
  'fundLink' : '펀드',
  'teamLink' : '팀',
  'newsroomLink' : '뉴스룸',
  'partnersLink' : '파트너',
  'contactUsLink' : '문의하기',
  'tokenTitle' : '토큰',
  'priceTitle' : '가격',
  'sinceICOTitle' : 'SINCE ICO',
  'getTokenTitle' : '토큰 얻기',
  'liveCoinTitle' : 'LIVECOIN',
  'liquiTitle' : 'LIQUI',
  'hitbtcTitle' : 'HITBTC',
  'cossTitle' : 'COSS.IO',
  'coinExchangeTitle' : '코인 교환',
  'validCountryCode' : '유효한 국가 코드를 입력해주세요.',
  'validPhoneNumber' : '유효한 핸드폰 번호를 입력해주세요.',
  'etherRqr' :'이더를 입력해주세요.',
  'ethereumRqrd' : '이더리움을 입력해주세요.',
  'validEther' : '유효한 이더를 입력해주세요.',
  'referralCode' : '추천 코드',
  'referralCodeLenth' : '추천 코드는 8자이어야 합니다.',
  'submit' : '가입',
  'clickHere': '여기를 클릭하세요.',
  'toGetStarted':'시작하기.',
  'noTransactions': '거래 내역이 없습니다.',
  'noReferralCode': '추천 코드가 없습니다.',
  'currency':'통화',
  'ether':'이더',
  'enterValue':'숫자를 입력하세요.',
  'prfToken':'프루프 토큰',
  'destination':'보낼 주소',
  'amount':'액수',
  'getEthereum':'이더 얻기',
  'doYouEther':'이더가 이미 있으신가요?',
  'yesIDo':'네, 있습니다.',
  'noNeedEther':'아니요, 이더가 필요합니다.',
  'whatIsThis':'이것이 무엇인가요?',
  'buyBitcoin':'Shapeshift 통해서 비트코인으로 이더 구매하기',
  'buyEtherVia':' 통해서 비트코인으로 이더 구매하기',
  'shapeShift':'Shapeshift ',
  'address':'주소',
  'here':'여기',
  'ethBalance':'이더리움 잔액',
  'tokenBalance':'프루프 토큰 잔액',
  'backUpWallet':'지갑 백업하기',
  'loadWallet':'지갑 충전하기',
  'sendAddress':' 이 주소로 이더 보내기',
  'ethereumAddress':'이더리움 주소',
  'prchasePRTF':'PRTF 구매하기',
  'eth':'ETH',
  'buyProofToken':'프루프 토큰 구매하기',
  'bitcoinPrg':'여기로 비트코인을 보내면 Shapeshift API 를 통해 이더리움이 지갑으로 전송됩니다. Shapeshift의 현재 요율에 따라 거래 수수료가 부과됩니다. 더 많은 정보를 찾을 수 있습니다.',
  'userInfo':'사용자 정보',
  'phnNumber':'핸드폰 번호',
  'chngePhnNumber':'핸드폰 번호 수정',
  '2facotrLogin':'2 Factor Authentication open login',
  'importWalletFile':'새로운 지갑 파일 불러오기',
  'warningFile':'(경고, 현재 지갑이 삭제됩니다.)',
  'deleteCurrentWallet':'(경고, 현재 지갑이 삭제됩니다.)',
  'changePassword':'비밀번호 수정',
  'update':'업데이트',
  'enterOldPassword':'현재 비밀번호를 입력하세요.',
  'enterWalletPassword':'지갑 비밀번호를 입력하세요.',
  '2factorAuthentication':'2 Factor Authentication',
  'PRTFBoughtSuccess':'성공적으로 PRTF를 구매 하였습니다.',
  'PRTFBoughtFailed':'PRTF가 구매되지 않았습니다.',
  'tokenTransferSuccess':'성공적으로 프루프 토큰이 이체되었습니다.',
  'tokenTransferfailed':'프루프 토큰 이체에 실패 하였습니다.',
  'invalidOldPwd':'이전 비밀번호가 유효하지 않은 번호입니다.',
  'invalidFile':'유효하지 않은 파일입니다.',
  'invalidPwd':'비밀번호가 유효하지 않은.',
  'contractAddress': '계약서 주소',
  'referCodeSuccess': '프로모션 코드가 성공적으로 발행되었습니다.',
  'yourReferCode': '귀하의 프로모션 코드입니다: ',
  'sendEtheriumWallet': '이더리움을 플랫폼 지갑으로 보내기',
  'buyPrftTokens':  'SYM 토큰 구매',
  'yourReferCodeLink': '다음은 귀하의 프로모션 코드 링크입니다.',
  'sendInfoNote': '토큰 구매 기간이나 거래 트래픽이 많을 때는 시간이 더 소요될 수 있습니다.',
  'referralInfoMsg': '귀하의 이메일과 이더리움 주소를 적어주시면 귀하의 친구들과 커뮤니티가 확인할 수 있는 프로모션 코드가 생성됩니다. 토큰 판매 종료 후 12월 17일까지 ETH 프로모션 코드로 발생된 매출의 1%를 귀하께서 제공해주신 이더리움 주소를 통해 받아보실 수 있습니다. 이메일로 귀하의 프로모션 코드와 링크를 보내드립니다.',
  'resendOtp':  '비밀번호 인증 코드 재전송',
  'transactionHash':'거래 해쉬: ',
  'transactionMsg': '귀하의 거래가 블록체인에 등록되었습니다. 해당 거래가 채굴되고 확인이 완료될 때까지 기다려 주세요. 거래 트래픽이 많을 때는 확인하는데 한 시간 이상이 소요될 수 있습니다.',
  'amountSendSucess': ' 금액이 성공적으로 이체 되었습니다.',
  'amountSendFail': '금액 이체에 실패하였습니다.',
  'referralStatus': '프로모션 코드 상태',
  'listEmpty': '프로모션 코드 목록이 비어있습니다.',

  'privacyStatement':'PRIVACY STATEMENT',
  'pSection1':'SECTION 1 - WHAT DO WE DO WITH YOUR INFORMATION?',
  'pSection11':'When you purchase something from our site, as part of the buying and selling process, we collect the personal information you give us such as your name, address and email address.',
  'pSection12':'When you browse our site, we also automatically receive your computer’s internet protocol (IP) address in order to provide us with information that helps us learn about your browser and operating system.',
  'pSection13':'Email marketing (if applicable): With your permission, we may send you emails about our site, new products and other updates.',
  'pSection2':'SECTION 2 - CONSENT',
  'pSection21':'How do you get my consent?',
  'pSection22':'When you provide us with personal information to complete a transaction, verify your email, create a transaction on [Proof Smart Contract as designated on https://www.TokenSale.com], arrange for a delivery or return a purchase, we imply that you consent to our collecting it and using it for that specific reason only.',
  'pSection23':'If we ask for your personal information for a secondary reason, like marketing, we will either ask you directly for your expressed consent, or provide you with an opportunity to say no.',
  'pSection24':'How do I withdraw my consent?',
  'pSection25':'If after you opt-in, you change your mind, you may withdraw your consent for us to contact you, for the continued collection, use or disclosure of your information, at anytime, by contacting us at',
  'pSection3':'SECTION 3 - DISCLOSURE',
  'pSection31':'We may disclose your personal information if we are required by law to do so or if you violate our Terms of Service.',
  'pSection4':'SECTION 4 - Infrastructure',
  'pSection41':'Our site is hosted on cloud-based servers under a domain-name of ‘www.TokenSale.com’. Our databases are located on external servers and all information has been either encrypted or otherwise made unavailable to members, developers, and representatives of the platform, company, or other apparatus of DeltaBox OU operated as “Proof Suite.',
  'pSection411':'Payment',
  'pSection42':'Payment occurs through blockchain-enabled ‘wallets’.  A wallet is a set of keys which lock and unlock transactions on a public ledger deployed on P2P architecture.  Due to the public nature of Blockchains, occurrences are often unpredictable and unpreventable.  The platform holder does not store, save, or record any of the data held on the platform.  Any loss of funds due to mishandling of client-side assets by user are the sole responsibility of the user.',
  'pSection5':'SECTION 5 - THIRD-PARTY SERVICES',
  'pSection51':'In general, the third-party providers used by us will only collect, use and disclose your information to the extent necessary to allow them to perform the services they provide to us.  These services are limited to fulfilment of KYC/AML practices as pursuant to all applicable compliance statutes and regulations and/or the monitoring of site services in the interest of protecting platform data and functionality.',
  'pSection52':'For these providers, we recommend that you read their privacy policies so you can understand the manner in which your personal information will be handled by these providers.  Any providers utilizing information for data gathering shall be disclosed on publishing materials which can be found at medium.com/proof-of-fintech or medium.com/proof-of-fintech-devblog.',
  'pSection53':'In particular, remember that certain providers may be located in or have facilities that are located in a different jurisdiction than either you or us. So if you elect to proceed with a transaction that involves the services of a third-party service provider, then your information may become subject to the laws of the jurisdiction(s) in which that service provider or its facilities are located.',
  'pSection54':'Once you leave our site’s website or are redirected to a third-party website or application, you are no longer governed by this Privacy Policy or our website’s Terms of Service.',
  'pSection511':'Links',
  'pSection55':'When you click on links on our site, they may direct you away from our site. We are not responsible for the privacy practices of other sites and encourage you to read their privacy statements.',
  'pSection6':'SECTION 6 - SECURITY',
  'pSection61':'To protect your personal information, we take reasonable precautions and follow industry best practices to make sure it is not inappropriately lost, misused, accessed, disclosed, altered or destroyed.',
  'pSection62':'If you provide us with your credit card information, the information is encrypted using secure socket layer technology (SSL) and sited with a AES-256 encryption.  Although no method of transmission over the Internet or electronic storage is 100% secure, we follow all PCI-DSS requirements and implement additional generally accepted industry standards.',
  'pSection7':'SECTION 7 - AGE OF CONSENT',
  'pSection71':'By using this site, you represent that you are at least the age of majority in your state or province of residence, or that you are the age of majority in your state or province of residence and you have given us your consent to allow any of your minor dependents to use this site.',
  'pSection8':'SECTION 8 - CHANGES TO THIS PRIVACY POLICY',
  'pSection81':'We reserve the right to modify this privacy policy at any time, so please review it frequently. Changes and clarifications will take effect immediately upon their posting on the website. If we make material changes to this policy, we will notify you here that it has been updated, so that you are aware of what information we collect, how we use it, and under what circumstances, if any, we use and/or disclose it.',
  'pSection9':'QUESTIONS AND CONTACT INFORMATION',
  'pSection91':'If you would like to: access, correct, amend or delete any personal information we have about you, register a complaint, or simply want more information contact our Privacy Compliance Officer at',
  'pSection92':'hello@proofsuite.com or by mail at Proof Suite',
  'pSection10':'[Re: Privacy Compliance Officer]',
  'pSection101':'[Roosikrantsi 2-K068, Tallinn city, Harju county, 10119]',
  'tokenSalesTerms':'P003_53861 Token Sale Terms',
  'tstHeader':'There is a total supply of 2,362,062 Proof tokens. 50% of tokens (1,181,031) will be offered for sale in the initial coin offering. Proof tokens will be offered for .088 Ether/token on Nov. 1st, 2017 at 10pm (GMT+9).',
  'ttp1':'This Right Purchase Agreement (the “Agreement”) is made and entered into as of 2017-10-23 (“Effective Date”) by and between whose address is (the “Purchaser” or the “lien holder”) and whose is located at (the “Seller” or “ Owner”). ',
  'ttp2':'The ‘Token’ defined herein is an abstract, digital marker allowing the creation and access to various products and services.  It is not a financial asset nor is its intended purpose to act as a representative of stake, entitlement to fiduciary rights, and/or traded for financial gain.  Doing so forfeits the user to protections laid out herein.  Upon issuance, Delta Box OU, operating as “Proof Suite” hereby known as “Proof” holds no liability for the Token destruction, trade, or loss.  The Token is not intended to hold value but rather to be purchasable as a means to access technological services and products including and not limited to, the AMP Market, The Proof Dashboard, Proof Telegram, Proof Tokensale Maker, and/or Proof Legal Agreement Generator.  Any loss or gain incurred by the third-party sale of The Token is not the responsibility of Proof or any related entities.',
  'ttp3':'WHEREAS, Parties hereto desire to enter into this Agreement. ',
  'ttp4':'NOW, THEREFORE, in consideration of the mutual interest and covenants herein contained and for other good and valuable consideration, the receipt and sufficiency of which are hereby acknowledged, and intending to be legally bound hereby, the Parties agree as follows: This Agreement shall be referred to as “P003_53861” for the subsequent Token Purchase Agreement. ',
  'ttp5':'1. DEFINITIONS. “Token” means a digitized portion or unit of the syndicated ownership of the Right under the Agreement P003_53861. “Token Holder” means a buyer of the Token that represents a  crypto-asset through a Smart Contract created by Purchaser herein. “Smart Contract” means terms and conditions for a Trading Instrument written in a programming language or asset protocol into the Ethereum blockchain.',
  'tokenTransferAgreement':'Token Transfer Agreement',
  'ttp6':'Subject to an existing Right of Ownership Token Transfer Agreement or otherwise proclaimed possession of ownership of the underlying asset ("the "), referenced hereafter as "P003_53861", , (hereafter the “Token Issuer”) whose address is (the “Purchaser” or the “lien holder”) hereby agrees to tokenize his ownership of the Right granted under the Agreement P003_53861, (the “Token to Revenue”).',
  'ttp7':'Uploading this Agreement on the blockchain will be hashed and referred in code of a Smart Contract generated by the Token Issuer.',
  'ttSection1':'1. SALE OF THE Token.',
  'ttSection11':'1.1. The Token Issuer hereby agrees to issue Token(s) at the price marked on web services as of 2017-11-1 on the blockchain of the Token Issuer’s choice ().',
  'ttSection2':'2. TOKEN BUYER’S PAYMENT AS CONDITION PRECEDENT.',
  'ttSection21':'2.1. Token Buyer’s (defined in Section 14) payment for the Token(s) issued by Token Issuer under Section 1 is a condition precedent to the formation of this Agreement. There will no binding Agreement until the payment from the Token Buyer is appeared on the Token Issuer’s Proof Dashboard account.',
  'ttSection22':'2.2. Likewise, there will be no binding agreement with any subsequent token buyer unless the payment for the Token created hereunder made to the Token Holder at the moment of selling the Token. ',
  'ttSection3':'3. SMART CONTRACT.',
  'ttSection31':'For the purpose of recording the ownership of the Right created under the Agreement P003_53861, Token Issuer generates a Smart Contract. This Smart Contract facilitates the direct transfer of the Right created to an individual or an entity that makes the payment for the Token representing the ownership of the Right created under the Agreement K003-2017 (the “Token Holder”). ',
  'ttSection4':'4. TOKEN HOLDER’S RIGHT. ',
  'ttSection41':'4.1. Subject to the Agreement P003_53861, all Token Holder(s) will be granted the right to set a new price for the purchased token hereunder, provided that he/she cannot interfere or enforce in the Owner’s decision regarding the subject to the Agreement P003_53861.',
  'ttSection42':'4.2. Subject to the Agreement P003_53861, Token Holder(s)’s Right does not create any type of a lien on the subject to the Agreement P003_53861. Token Holder’s Right will be limited to the Right to claim the amount of the Income promised by the Owner to Token Issuer under the Agreement P003_53861.',
  'ttSection5':'5. RIGHT OWNER’S WARRANTIES AND DUTIES.',
  'ttSection51':'Token Issuer and subsequent Token Holder hereby represent and warrant that, to the best of his/her knowledge, he/she is the sole lawful owner of the Token created under the Agreement P003_53861 and free and clear of any liens and encumbrances except the ones disclosed to Token Issuer from the Owner under the Agreement P003_53861. Token Issuer and each subsequent Token Holder(s) have full right, power and authority to sell and transfer his/her Right created under the Agreement P003_53861. Token Issuer and each subsequent Token Holder also warrant that he/she does not currently know of and has no reason to know of any third party claim to any right, title, or use of the Right created under the Agreement P003_53861 except the ones disclosed to Token Issuer from the Owner under the Agreement P003_53861. Token Issuer and each subsequent Token Holder did not and will not execute any agreement in conflict with this Agreement. Once a token purchaser makes the full payment pursuant to Section 1, Token Issuer will take any actions that may be necessary or desirable to protect and perfect the Purchaser’s Right created under the Agreement P003_53861.',
  'ttSection6':'6. ASSUMPTION OF RISK.',
  'ttSection61':'Each Token Holder bears the risk of loss when purchasing a Token representing the ownership of the Right created under the Agreement P003_53861. Token Issuer will not be responsible for and will not be liable for any loss arising from: (a) failure or malfunction of hardware, software, server, and internet connections; (b) malicious software introduction; (c) the third party may obtain unauthorized access to information stored within buyer’s account, including, but not limited to Buyer’s storage address and private key; (d) forgotten passwords and/or private keys; and (e) incorrectly constructed transactions or mistyped account address.',
  'ttSection7':'7. DISCLAIMER.',
  'ttSection71':'This Token subject to the Agreement P003_53861 is not a consumer good and sold on an “as is” and “as-available” basis. Token Holder(s) bears the entire risk, Token Issuer sells the Token to Token Holder(s) without any warranty of fitness for a particular purpose, and Token Holder(s) acknowledges that no warrant of fitness could be offered because of the many future technical and legal uncertainties regarding the Token.',
  'ttSection8':'8. TAX.',
  'ttSection81':'Token Issuer is not responsible for any taxes or any other costs related to purchasing the Token created under the Agreement P003_53861.',
  'ttSection9':'9. NO DAMAGES.',
  'ttSection91':'Token Issuer will never be liable to Token Holder(s) for consequential and any kind of damages, including but not limited to lost profits. ',
  'ttSection10':'10. MARKET RISK.',
  'ttSection101':'All Token Holder(s) understands that this Token is a new and relatively untested exchange medium. Token Holder(s) therefore understands that Token Issuer cannot predict how the value of the Token will change, the consumer demand for the Token, technical difficulties in or modification to the peer-to-peer blockchain network, change of regulations, and all other obstacles that a peer-to-peer blockchain network might face. All Token Holder(s) affirmatively represents that he/she is a sophisticated blockchain users and therefore knowingly assumes all known and unknown risk of loss. All Token Holder(s) has not recourse whatsoever against Token Issuer for damages or liability suffered by Token Holder(s) due to the market condition or whatsoever causes.',
  'ttSectionE11':'11. RISK OF FINANCIAL REGULATION.',
  'ttSectionE111':'All Token Holder(s) understands that the Token is a relatively new technology and no one can predict how the government for each country may apply and enforce the existing laws or regulate the Token or other peer-to-peer blockchain based exchange technologies in the future. All Token Holder(s) understands that there is a high level of uncertainty, and all Token Holder(s) assumes that all financial regulatory risk inherent in operating and transferring the Token. ',
  'ttSectionE112':'All Token Holder(s) has no recourse whatsoever against Token Issuer for damages, civil and criminal, suffered by each Token Holder(s) due to regulatory enforcement. Token Issuer does not and cannot warrant that the exercise or transfer of the Token is legal in all specific jurisdiction of each country. Token Issuer has not duty to advise or warn to each Token Holder(s) and each Token Holder(s) will not advise or warn Token Issuer about any particular legal or regulatory requirement(s). Each Token Holder(s) is solely obligated to understand the laws and regulations of its local jurisdiction before exercising, selling, or purchasing the Token, and Token Holder(s) is solely responsible for any of its actions that may be unlawful. ',
  'ttSectionE12':'12. DEFINITIONS.',
  'ttSectionE121':'“Token to Revenue” means a digitized portion or unit of the syndicated ownership of the Right created under the Agreement P003_53861. “Token Holder(s)” means a buyer(s) of the Token representing an ownership of the Right through the Smart Contract created by the Token Issuer hereunder. “Smart Contract” means terms and conditions for a legally effective Instrument written in programming language or asset protocol into the blockchain of Token Issuer’s choice. “Token Buyer” means that a party (an individual, legal entity, or authorized person representing an organization) that intends to buy the Token initially issued by Token Issuer hereunder.',
  'ttSectionE13':'13. DISPUTE RESOLTUION.',
  'ttSectionE131':'Informal Resolution. If either Token Issuer or Token Holder has any concerns regarding a breach under this Agreement, the complaining party must first notify the other and allow the other party at least 30 days to remedy the claimed breach. Binding Arbitration. Any dispute arising out of or relating to this Agreement, or the breach thereof, shall finally settled under the Rules of Arbitration of the International Chamber of Commerce by one or three arbitrator, and judgement upon the award rendered the arbitrators may be entered in a court in jurisdiction. The arbitration will be conducted in the English language, in accordance with the international Arbitration Rules of the Commercial Arbitration Board.',
  'ttSectionE14':'14. MISCELLANEOUS.',
  'ttSectionE141':'14.1. No Conditions to Effectiveness; Entire Agreement. There are no conditions to the effectiveness of this Agreement. This Agreement contains the entire agreement and understanding of the Parties hereto, and supersedes any prior agreements or understandings between or among the Parties hereto, which respect to the subject matter hereof. ',
  'ttSectionE142':'14.2. Governing Law. This Agreement, and the right of the Parties hereto, shall be governed by, construed and enforced in accordance with the laws of regardless of the conflict of laws principle. Any action in respect of, or concerning, this Agreement shall be litigated solely in and both Parties consent to jurisdiction of the person and venue solely in . ',
  'ttSectionE143':'14.3. Amendment and Waivers. This Agreement may be amended only by an instrument in writing signed by the Parties hereto. No waivers of or exceptions to any term, condition or provision of this Agreement, in any one or more instances, shall be deemed to be, or construed as, a further or continuing waiver of any such term, condition or provision. ',
  'ttSectionE144':'14.4. Severability. If any provision of this Agreement is held to be invalid or unenforceable, the validity and enforceability of the remaining provisions of this Agreement shall not be affected thereby. ',
  'ttSectionE145':'14.5. Each party, in entering into this Agreement, acts as an independent party and nothing herein shall be construed to create a partnership or joint venture between the Parties or to constitute agency of an sort. Neither party shall have the authority to bind the other. ',
  'ttSectionE146':'14.6. Force Majeure. A party is not liable for failure to perform the party’s obligations if such failure is as a result of Acts of God including: fire, flood, earthquake, storm, hurricane or other natural disaster), war, invasion, act of foreign enemies, hostilities (regardless of whether war is declared), civil war, rebellion, revolution, insurrection, military or usurped power or confiscation, terrorist activities, nationalization, government sanction, or government prohibition or regulation preventing the trade of blockchain-backed token(s).  The issuer of the token accepts no liability or responsibility for the corresponding use of the token.',
  'ttSectionE147':'By purchasing, trading, or accessing a proof instrument relating to referenced tokensale above, you agree to all terms of this agreement and all corresponding to the Terms and Conditions and Privacy Policy to be granted access to alongside this document.',
  'tcHeader':'PROOF TOKENSALE TERMS AND CONDITIONS',
  'tcp1':'Last Updated: 23 October, 2017 Please read these terms of token sale carefully. By purchasing SYM Tokens from Deltabox operating as Proofsuite, a private limited company organized under the laws of Estonia (“Proof Suite” or the “Company”) you will be bound by these Terms of token sale and all terms incorporated herein by reference.',
  'tcp2':'Note that Section 13 contains a binding arbitration clause and class action waiver, which affect your legal rights. If you do not agree to these terms of token sale, do not make any contribution to the Company and do not purchase SYM tokens. ',
  'tcp3':'Your purchase of SYM Tokens during the public sale from the Company is and will be subject to these terms of token sale (the "Terms and Conditions"). Each of you and the Company is a "Party" and, together, the "Parties" hereto. If you have any questions regarding these Terms and Conditions, please contact us hello@proofsuite.com.',
  'tcp4':'This Token Purchase Agreement (the “Agreement”) contains the terms and conditions that govern your use of the purchase ERC-20 compatible tokens distributed on the Ethereum blockchain (the “SYM Tokens”) and is an agreement between you or the entity that you represent (“Purchaser” or “you”) and the Company. The Buyer and the Company are herein referred to individually as a “Party” and collectively, as the “Parties”. ',
  'tcp5':'IMPORTANT INFORMATION: PLEASE READ THIS AGREEMENT CAREFULLY AND IN ITS ENTIRETY. ',
  'tcp6':'WHEREAS, The Company is issuing up to 2.4M Proof Tokens (“SYM Tokens”) during the Company’s token sale, commencing on November 1, 2017, which are tokens of utility that can be used to participate in the Company’s decentralized marketplace and in the Company’s Assurance Market Protocol (“AMP”).',
  'tcp7':'WHEREAS, The Company is selling up to 1.1M Proof Tokens (“SYM Tokens”) during the Company’s token sale (“Token Sale”), commencing on November 1, 2017',
  'tcp8':'WHEREAS, After the Token Sale, the Company shall allow to transfer SYM Tokens, which are ERC20 compliant liquidity tokens- to Ethereum wallet holders.',
  'tcp9':'NOW, THEREFORE, in consideration of the mutual representations, warranties and agreements contained in this Agreement, and for other good and valuable consideration, the receipt and sufficiency of which are hereby acknowledged, Company and Buyer hereby agree as follows:',
  'tcSection1':'1. Pre-Sale of SYM Tokens.',
  'tcSection11':'(a) Issuance and Sale Cap. The Company shall issue up to 300,000 SYM Presale Tokens in the pre-sale (the "Pre-Sale Cap"). ',
  'tcSection12':'(b) Price. The price of SYM Presale Tokens during the Pre-sale is 0.075 ETH',
  'tcSection13':'(c) Pre-Sale Allocation. As a result of (i) any flags on our standard anti-money-laundering screen, the quantity of SYM tokens allocated to Purchaser may be zero or less than the total amount subscribed by the Purchaser.',
  'tcSection14':'(d) SYM Pre-sale Tokens will be automatically converted into SYM Tokens under the terms and conditions herein.',
  'tcSection2':'2. Issuance and Sale of SYM Tokens in Token Sale (“Token Sale”).',
  'tcSection21':'(a) Issuance and Sale Cap. The Company shall issue up to 2.3M SYM Tokens before the end of the Token Sale. The Company shall be selling up to 1.1M SYM Tokens. The total amount of SYM tokens issued at Token Sale will not exceed 250,000 ETH.',
  'tcSection22':'(b) Price. The price of SYM Tokens during the Token Sale shall be as follows: (i) The first 5% of SYM Tokens will be priced 0.0748 ETH; (ii) The following 5% SYM Tokens will be priced 0.0792 ETH; The following 5% SYM Tokens will be price 0.0836 ETH. The remaining tokens price will be 0.088 ETH.',
  'tcSection23':'(c) Token Sale Cap; Refunds and Chargebacks. The Company shall stop accepting payments when the Token Sale Cap is hit. Purchasers who make payments after the Token Sale has been hit shall have chargebacks at their expense. The time of payment shall be the time the transaction is mined into the blockchain. A detailed description of the token distribution mechanism shall be published in the Company official blog at https://medium.com/proof-of-fintech.',
  'tcSection24':'(d) Payments The Company shall accept payment in ETH. Time of payment shall equal the time the transaction is mined into the blockchain. ',
  'tcSection3':'3. Issuance and Sale of SYM Tokens.',
  'tcSection31':'(a) Issuance and Sale Cap. After the end of the Token Sale, the Company shall enable SYM Tokens transfers between Ethereum Wallet holders, which will have utility in the Proof Suite Assurance Marketplace Protocol.',
  'tcSection32':'(b) Conversion of SYM Presale Tokens. 100% of the SYM Presale tokens issued shall be converted by smart contract into SYM tokens at the ratio of 1 SYM Token for 1 SYM Presale Token under the conditions herein.',
  'tcSection4':'4. Delivery of SYM Tokens.',
  'tcSection41':'(a) Purchaser must provide the personal information requested by the Company in Section 6(b) below within twelve (12) months of the Purchaser’s contribution in order to receive their SYM Tokens. If Purchaser fails to provide the requested information, the Company reserves the right to refuse delivery of the SYM Tokens and will not be liable for any refunds of the Purchaser’s contribution. \n',
  'tcSection42':'(b) Provided that Purchaser has provided a token delivery wallet address and the personal information as outlined in Section 4(a) and Section 6(b), the Company will deliver the quantity of SYM Tokens purchased by Purchaser (as adjusted pursuant to Section 1(b) or 2(b) within three (3) weeks of the end of Token Sale (the “Token Delivery Deadline”); provided, however, that Company reserves the right to extend the Token Delivery Deadline for up to two (2) additional weeks if necessary to address any unanticipated technical difficulties. For the avoidance of doubt, any such extension shall not affect the obligation of Company and the Purchaser to make and take delivery, respectively, of the SYM Tokens purchased.',
  'tcSection5':'5. Purpose and Use of Tokens in the Ecosystem. ',
  'tcSection51':'(a) The SYM Tokens are utility tokens that shall be used in the Company’s decentralized asset market place via the AMP protocol in the following ways (and as more fully described in the Company’s whitepaper at https://Proof Suite.global/media/files/whitepaper_en.pdf):',
  'tcSection511':'● Provide part of the AMP mechanism design incentive by receiving contributions from transfers to the Crypto-Fiat Smart Contracts.',
  'tcSection512':'● Provide part of the AMP mechanism design incentive by receiving contributions from transfers to the Currency Prediction Market Smart Contract; ',
  'tcSection513':'(b) Purchase, ownership, receipt, or possession of SYM Tokens or SYM Presale Tokens (collectively the “Tokens”) carries no rights, express or implied, other than the right to use such Tokens as a means to participate, interact or transact on the Company’s platform and ecosystem, if successfully completed and deployed. In particular, Purchaser understands and accepts that Tokens do not represent or confer any ownership right or stake, share, security, or equivalent rights, or any right to receive future revenue shares, intellectual property rights or any other form of participation in or relating to the and its corporate affiliates, other than any rights relating to the provision and receipt of services from Company, subject to limitations and conditions in this Agreement. The Tokens are not intended to be a digital currency, security, commodity, or any kind of financial instrument. ',
  'tcSection6':'6. Eligibility. ',
  'tcSection61':'(a) In order to be eligible to participate in the Company’s token sale, Purchaser must have an Ethereum wallet that supports the ERC-20 standard in order to receive any Tokens purchased from Company (the “Token Receipt Address”). Company reserves the right to prescribe additional guidance regarding specific wallet requirements. (b) In order to be eligible to participate in the Company’s token sale, Purchasers must be eighteen (18) years of age. (c) In order to be eligible to participate in the Company’s token sale, Purchasers must also enter all required personal information in the purchase flow and thereafter, including first name, last name, email, country, phone number, etc and provide any requested identity verification documents requested by the Company . (d) You are not eligible and you are not allowed to purchase any SYM Tokens if you are a citizen or resident (tax or otherwise) of Singapore, or other Singapore Person. "Singapore Person" is generally defined as a natural person, residing in Singapore, or any entity organized or incorporated under the laws of Singapore. (e) You are not eligible and you are not to purchase any SYM Tokens if you are a citizen or resident (tax or otherwise) of the People\'s Republic of China ("PRC"), or other PRC Person. "PRC Person" is generally defined as a natural person, residing in the People\'s Republic of China, or any entity organized or incorporated under the laws of the People\'s Republic of China. (f) You are not eligible and you are not to purchase any SYM Tokens if you are a citizen or resident (tax or otherwise) of South Korea. (g) You are not eligible and you are not to purchase any SYM Tokens, unless you are an "Accredited Investor" as that term is defined in the Securities Act of 1933, if you are a green card holder of the United States or a citizen or resident (tax or otherwise) of the United States of America, or other U.S. Person. "U.S. Person" is generally defined as a natural person, residing in the United States, including American Samoa, Guam, Northern Mariana Islands, Puerto Rico, U.S. Virgin Islands, or any entity organized or incorporated under the laws of the United States. U.S. citizens living abroad may also be deemed "U.S. Persons" under certain rules.',
  'tcSection7':'7. Cancellation; Refusal of Purchase Requests.',
  'tcSection71':'All Token purchases from the Company are final, and there are no refunds or cancellations except as may be required by applicable law or regulation. Company reserves the right to refuse or cancel Token purchase requests at any time in its sole discretion.',
  'tcSection8':'8. Token Allocation.',
  'tcSection81':'Important information about the Company’s creation and intended use of the Tokens is provided in the Company’s whitepaper at https://Proof Suite.global/static/whitepaper.pdf. By purchasing Tokens, Purchaser acknowledges that Purchaser has read and understands the whitepaper. ',
  'tcSection9':'9. Acknowledgment and Assumption of Risks.',
  'tcSection91':'Purchaser acknowledges and agrees that there are risks associated with purchasing Tokens, owning Tokens, and using Tokens for the provision or receipt of services on Company. BY PURCHASING TOKENS, PURCHASER EXPRESSLY ACKNOWLEDGES AND ASSUMES THESE RISKS. ',
  'tcSection10':'10. Security.',
  'tcSection101':'Purchaser is responsible for implementing reasonable measures for securing the wallet, vault or other storage mechanism Purchaser uses to receive and hold Tokens purchased from Company, including any requisite private key(s) or other credentials necessary to access such storage mechanism(s). If Purchaser’s private key(s) or other access credentials are lost, Purchaser may lose access to Purchaser’s Tokens. Company is not responsible for any losses, costs or expenses relating to lost access credentials. ',
  'tcSectionE11':'11. Personal Information.',
  'tcSectionE111':'Company may determine, in its sole discretion, that it is necessary to obtain certain information about Purchaser in order to comply with applicable laws or regulations in connection with selling Tokens to Purchaser. Purchaser agrees to provide Company such information promptly upon request. Purchaser acknowledges that Company may refuse to sell Tokens to Purchaser until Purchaser provides such requested information and has determined that it is permissible to sell Purchaser Tokens under applicable laws or regulations. ',
  'tcSectionE12':'12. Taxes.',
  'tcSectionE121':'Any amounts that Purchaser pays for Tokens are exclusive of all applicable taxes. Purchaser is responsible for determining what, if any, taxes apply to Purchaser’s purchase of Tokens, including, for example, sales, use, value added, and similar taxes. It is also Purchaser’s responsibility to withhold, collect, report and remit the correct taxes to the appropriate tax authorities. The Company is not responsible for withholding, collecting, reporting, or remitting any sales, use, value added, or similar tax arising from the Purchaser’s purchase of Tokens.',
  'tcSectionE13':'13. Dispute Resolution; Arbitration',
  'tcSectionE131':'(a) Binding Arbitration. Except for any disputes, claims, suits, actions, causes of action, demands or proceedings (collectively, "Disputes") in which either Party seeks to bring an individual action in small claims court or seeks injunctive or other equitable relief for the alleged unlawful use of intellectual property, including, without limitation, copyrights, trademarks, trade names, logos, trade secrets or patents, you and the Company (i) waive your and the Company’s respective rights to have any and all Disputes arising from or related to these Terms resolved in a court, and (ii) waive your and the Company’s respective rights to a jury trial. Instead, you and the Company will arbitrate Disputes through binding arbitration (which is the referral of a Dispute to one or more persons charged with reviewing the Dispute and making a final and binding determination to resolve it instead of having the Dispute decided by a judge or jury in court). (b) No Class Arbitrations, Class Actions or Representative Actions. Any Dispute arising out of or related to these Terms is personal to you and the Company and will be resolved solely through individual arbitration and will not be brought as a class arbitration, class action or any other type of representative proceeding. There will be no class arbitration or arbitration in which an individual attempts to resolve a Dispute as a representative of another individual or group of individuals. Further, a Dispute cannot be brought as a class or other type of representative action, whether within or outside of arbitration, or on behalf of any other individual or group of individuals. (c) Notice; Informal Dispute Resolution. Each Party will notify the other Party in writing of any arbitrable or small claims Dispute within thirty (30) days of the date it arises, so that the Parties can attempt in good faith to resolve the Dispute informally. Notice to the Company shall be sent by email to the Company at legal@proofsuite.com. Notice to you shall be by email to the email address you provide to us. Your notice must include (i) your name, postal address, email address and telephone number, (ii) a description in reasonable detail of the nature or basis of the Dispute, and (iii) the specific relief that you are seeking. If you and the Company cannot agree how to resolve the Dispute within thirty (30) days after the date notice is received by the applicable Party, then either you or the Company may, as appropriate and in accordance with this Section 13, commence an arbitration proceeding or, to the extent specifically provided for in clause 13(a), file a claim in court.',
  'tcSectionE14':'14. Governing Law.',
  'tcSectionE141':'These Terms and Conditions and any Dispute or claim arising out of or in connection with their subject matter or formation (including non-contractual disputes and claims) shall be governed by and construed in accordance with Estonian Law. Any Dispute between the Parties arising out or relating to these Terms and Conditions that is not subject to arbitration under Section 13 hereof will be resolved in Estonian courts, and the Parties irrevocably agree that Estonian courts shall have exclusive jurisdiction to settle any such Dispute or claim.',

};
